services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - file=.env.nestjsapi
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3007:3007'
    environment: 
      - file=.env.mysql
